package model;

public enum ExperimentType {
  Q_WF_NGS_QUALITYCONTROL, Q_WF_MS_QUALITYCONTROL, Q_WF_MS_MAXQUANT, Q_SAMPLE_PREPARATION, Q_SAMPLE_EXTRACTION, Q_PROJECT_DETAILS, Q_NGS_VARIANT_CALLING, Q_NGS_SINGLE_SAMPLE_RUN, Q_NGS_MEASUREMENT, Q_NGS_MAPPING, Q_NGS_IMMUNE_MONITORING, Q_NGS_HLATYPING, Q_NGS_FLOWCELL_RUN, Q_NGS_EPITOPE_PREDICTION, Q_MS_MEASUREMENT, Q_EXPERIMENTAL_DESIGN, Q_WF_NGS_EPITOPE_PREDICTION, Q_WF_NGS_VARIANT_ANNOTATION, Q_WF_NGS_HLATYPING
}
